Chore - post merge
iotaledger/iota-wiki pull request #1007
Opened 2023-07-01 22:54 UTC by Dr-Electron

# Description of change

Updated the README and tried to make the setup easier where possible by removing redundant setups

## Links to any relevant issues

Fixes #994 

## Type of change

- Enhancement (a non-breaking change which adds functionality)
- Documentation Enhancement

## Change checklist

- [x] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [x] I have performed a self-review of my own changes
- [x] I have made sure that added/changed links still work
- [x] I have commented my code, particularly in hard-to-understand areas

2023-07-03 17:40 UTC, lucas-tortora submitted a review, later dismissed

2023-07-09 23:21 UTC, jlvandenhout requested changes

2023-07-09 23:21 UTC, jlvandenhout commented on README.md
> +3. Preview a specific environment with `yarn start:<environment>` where environment can be `iota`, `shimmer` or `next`.
```suggestion
4. Preview a specific environment with `yarn start:<environment>` where environment can be `iota`, `shimmer` or `next`.
```
Not technically necessary, but..

2023-07-09 23:21 UTC, jlvandenhout commented on README.md
> +The IOTA Wiki is maintained by the IF and community contributions are always welcome. The DX team and related Teams from the IF will review all issues and pull requests posted to this repository. If
```suggestion
The IOTA Wiki is maintained by the IF and community contributions are always welcome. The DX team and related teams from the IF will review all issues and pull requests posted to this repository. If you notice any mistakes, or feel something is missing, feel free to create an issue to discuss with the team or directly create a pull request with suggestions. Here is a basic workflow to open a pull request:
```

2023-07-10 09:56 UTC, jlvandenhout approved these changes

2023-07-10 10:48 UTC, merged