Restructure - Populate learn
iotaledger/iota-wiki pull request #1080
Opened 2023-08-03 18:26 UTC by lucas-tortora

# Description of change

Added content for the Learn section based on the miro board.

## Links to any relevant issues

fixes https://github.com/iotaledger/devx/issues/185

## Type of change

- Documentation Enhancement

## Change checklist

- [x] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [x] I have performed a self-review of my own changes
- [x] I have made sure that added/changed links still work
- [x] I have commented my code, particularly in hard-to-understand areas

2023-08-03 18:26 UTC, lucas-tortora commented
Still in draft as we need to define the sources for 2 articles.

2023-08-03 18:26 UTC, lucas-tortora commented
/create-preview

2023-08-04 13:35 UTC, lucas-tortora commented
the two missing 2.0 articles will be written by Billy.

2023-08-04 19:57 UTC, Dr-Electron requested changes

2023-08-04 19:57 UTC, Dr-Electron commented on docs/learn/iota2.0/core-concepts/data-structures.md
> +IOTA 2.0 used Ed25519 signatures to strengthen the security of transactions, making them safe and reliable.
used or uses?
```suggestion
IOTA 2.0 uses Ed25519 signatures to strengthen the security of transactions, making them safe and reliable.
```

2023-08-04 19:57 UTC, Dr-Electron commented on docs/learn/iota2.0/core-concepts/mana.md
> +Mana exists in two forms: stored on the unspent outputs and allotted to chosen accounts as BIC credits.
Practically it's three. Potential, Stored and Allotted :trollface: , But I guess that out of scope again

2023-08-04 19:57 UTC, Dr-Electron commented on docs/learn/iota2.0/core-concepts/mana.md
> +Mana exists in two forms: stored on the unspent outputs and allotted to chosen accounts as BIC credits.
But seeing that we mention it later in this article, maybe it should be mentioned here too?

2023-08-04 19:57 UTC, Dr-Electron commented on docs/learn/iota2.0/core-concepts/mana.md
> +Keep in mind that all validation blocks issued by nodes not selected for the committee will be discarded
Duplicate

2023-08-04 19:57 UTC, Dr-Electron commented on docs/learn/iota2.0/core-concepts/mana.md
> +## Mana Rewards
Should we mention the 1-2-3 rule here?

2023-08-04 19:57 UTC, Dr-Electron commented on docs/learn/iota2.0/core-concepts/networking.md
> +enabled if the node has at least four static peers. An `autopeering` module will use the specified entry nodes
Having four static peers is enforced now?

2023-08-04 19:57 UTC, Dr-Electron commented on docs/learn/iota2.0/core-concepts/validators.md
> +_Selection_. The committee is formed by taking a predetermined number of validators who have the largest stake.
Should we mention the random weighted selection here?

2023-08-04 19:57 UTC, Dr-Electron commented on docs/learn/iota2.0/core-concepts/validators.md
> +Each validator's stake is computed as the sum of the locked funds and the delegated stake from other nodes.
```suggestion
Each validator's stake is computed as the sum of the locked funds and the delegated stake from other accounts.
```
🤔

2023-08-04 19:57 UTC, Dr-Electron commented on docs/learn/iota2.0/core-concepts/validators.md
> +The next committee is formed by taking a predefined number of validators with the largest stake. When deciding between
```suggestion
The next committee is formed by taking a predefined number of random validators with the largest stake. When deciding between
```
Same us above. I think it's worth mentioning, no?

2023-08-04 19:57 UTC, Dr-Electron commented on docs/learn/stardust/core-concepts/consensus.md
> +The Coordinator is a temporary feature and will be removed with the upcoming IOTA 2.0 update.
Should we link to the 2.0 consensus here?

2023-08-04 19:57 UTC, Dr-Electron commented on docs/learn/stardust/core-concepts/consensus.md
We probably should mention white flag here somewhere and that all nodes follow it

2023-08-04 19:57 UTC, Dr-Electron commented on docs/learn/stardust/introduction.md
Tbh, not sure how I feel about this introduction. Maybe another formatting and structure would be better? Wdyt?

2023-08-04 22:28 UTC, jlvandenhout commented on docs/learn/chrysalis/core-concepts/binary-transaction-layout.md
> +Traditionally, some distributed ledger technologies (DLTs) used trinary data formats.
Not sure if we even need this whole section. Binary is the standard, trinary was the odd-ball in our own history, which we moved away from for very good reasons. imo we shouldn't reiterate that history here.

2023-08-07 13:43 UTC, Dr-Electron commented
Preview: https://iota-wiki-eikijzdtm-iota1.vercel.app/

2023-08-08 12:47 UTC, lucas-tortora commented on docs/learn/iota2.0/core-concepts/communication.md
> +included in recent slot commitments.
https://github.com/iotaledger/devx/issues/199

2023-08-08 18:29 UTC, lucas-tortora commented on docs/learn/chrysalis/core-concepts/white-flag-consensus.md
> +In the case of double spends, White Flag Consensus chooses to approve the first transaction that does not conflict with
I think it may be a bit much for this

2023-08-10 11:46 UTC, Dr-Electron commented on docs/learn/iota2.0/core-concepts/mana.md
> +## Mana Rewards
Can't find it right now. But it basically says that holders get mana rewards x1, delegators x2 and validators x3

2023-08-10 12:05 UTC, lucas-tortora commented
/create-peview

2023-08-10 12:49 UTC, Dr-Electron requested changes

2023-08-10 12:49 UTC, Dr-Electron commented on docs/learn/chrysalis/core-concepts/switch-to-UTXO.md
> +\Every address held a distinct balance value.
Why can't I make a suggestion? 😢 
Every address held a distinct balance value.

2023-08-10 12:49 UTC, Dr-Electron commented on docs/learn/chrysalis/core-concepts/switch-to-UTXO.md
> +With Chrysalis, IOTA moved away from the Winternitz One-Time Signature (WOTS) system to the Unspent Transaction Output (
Isn't this still a little bit weird 😅

I mean we switched from account based to UTXO
And from WOTS to Ed25519 addresses.

2023-08-10 12:49 UTC, Dr-Electron commented on docs/learn/chrysalis/core-concepts/switch-to-UTXO.md
> +- **Reattachments**: In cases where funds were received at an already spent address, it became possible for anyone to
I'm actually not sure if that is true? I thought the problem was somehow exposing your private key with every signature of an already spend address or something like that 🤔.

2023-08-10 13:02 UTC, Dr-Electron requested changes

2023-08-15 12:09 UTC, lucas-tortora commented on docs/learn/chrysalis/core-concepts/switch-to-UTXO.md
> +\Every address held a distinct balance value.
```suggestion
Every address held a distinct balance value.
```

2023-08-15 15:17 UTC, lucas-tortora commented
/create-preview

2023-08-15 18:42 UTC, Dr-Electron requested changes

2023-08-15 18:42 UTC, Dr-Electron commented on docs/learn/chrysalis/core-concepts/switch-to-UTXO.md
> +*Balance2**, and so on.
```suggestion
This meant the ledger tracked **Address1**, which was associated with **Balance1**, **Address2** was associated with **Balance2**, and so on.
```

2023-08-15 18:42 UTC, Dr-Electron commented on docs/learn/chrysalis/core-concepts/switch-to-UTXO.md
> +required to resolve these conflicts.
```suggestion
As with IOTA 2.0 a voting-based Coordicide solution was introduced, this meant that it was necessary to identify conflicts quickly and precisely so we could reduce the amount of voting required to resolve these conflicts.
```

2023-08-15 18:42 UTC, Dr-Electron commented on docs/learn/chrysalis/core-concepts/switch-to-UTXO.md
> +addresses only once.
As this is special to how IOTA did it and not in general to account models, I would remove this section. We could also replace it with a link to https://wiki.iota.org/tips/tips/TIP-0017/

2023-08-15 18:42 UTC, Dr-Electron commented on docs/learn/chrysalis/core-concepts/switch-to-UTXO.md
> +:::
```suggestion
:::tip Learn More

You can learn more about the [switch to UTXO](https://wiki.iota.org/tips/tips/TIP-0007) and [Ed25519](https://wiki.iota.org/tips/tips/TIP-0017/) in
the [TIPS section](../tips.md).

:::
```

2023-08-15 18:51 UTC, lucas-tortora commented on docs/learn/chrysalis/core-concepts/switch-to-UTXO.md
> +addresses only once.
```suggestion
```

2023-08-15 18:54 UTC, lucas-tortora commented on docs/learn/chrysalis/core-concepts/switch-to-UTXO.md
> +:::
```suggestion
:::tip Learn More
	
You can learn more about the [switch to UTXO](https://wiki.iota.org/tips/tips/TIP-0007) and [Ed25519](https://wiki.iota.org/tips/tips/TIP-0017/) in
the [TIPS section](../tips.md).

:::
```

2023-08-15 19:48 UTC, Thoralf-M commented on docs/learn/chrysalis/core-concepts/switch-to-UTXO.md
> +
```suggestion
### Reattachments

Another problem with using an account balance model is reattachments.
If somebody ever receives funds at an address already used to send tokens, anybody can just reattach the previous
transaction and empty the address again,
even if they do not control the private key.
```

or even better

```suggestion
```
:trollface:

2023-08-15 19:50 UTC, Thoralf-M commented on docs/learn/chrysalis/core-concepts/switch-to-UTXO.md
> +
Because this has nothing to do with Account vs UTXO

2023-08-15 19:52 UTC, Dr-Electron requested changes

2023-08-15 19:52 UTC, Dr-Electron commented on docs/learn/chrysalis/core-concepts/switch-to-UTXO.md
> +\*Balance2\*\*, and so on.
```suggestion
This meant the ledger tracked **Address1**, which was associated with **Balance1**, **Address2** was associated with **Balance2**, and so on.
```

2023-08-15 19:52 UTC, Dr-Electron commented on docs/learn/chrysalis/core-concepts/switch-to-UTXO.md
> +funds.
```suggestion
It took a lot of work to determine which of multiple transactions performed a double spend and which used legitimate funds.
```

2023-08-15 19:52 UTC, Dr-Electron commented on docs/learn/chrysalis/core-concepts/switch-to-UTXO.md
> +Every coin on an address can be uniquely identifiable, and every transaction names the exact coins it wants to move.
```suggestion
```

I would remove this. It is confusing at best and coins if kept should be replaces with Native tokens. But still weird

2023-08-15 19:59 UTC, Thoralf-M commented on docs/learn/chrysalis/core-concepts/switch-to-UTXO.md
> +Before Chrysalis, IOTA used an account balance model to track addresses.
```suggestion
Before Chrysalis, IOTA used an account balance model to track balances.
```

2023-08-15 20:04 UTC, Dr-Electron approved these changes
I think we can merge this 👍

2023-08-15 20:04 UTC, merged