Fix absolute links to old Shimmer and Next environments
iotaledger/iota-wiki pull request #1147
Opened 2023-09-01 13:36 UTC by jlvandenhout

# Description of change

We still had some absolute links to the Shimmer and Next environments.

## Type of change

- Documentation Fix

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [x] I have performed a self-review of my own changes
- [ ] I have made sure that added/changed links still work

2023-09-01 13:58 UTC, jlvandenhout commented
@Phyloiota maybe you can help out with resolving those last few governance links?

2023-09-02 12:51 UTC, jlvandenhout commented on docusaurus.config.js
> -        ],
@Dr-Electron why does it remove the redirects? 🤔 something went wrong in the rebase?

2023-09-02 18:13 UTC, jlvandenhout commented on docusaurus.config.js
> -        ],
Fixed it by editing your commit

2023-09-02 19:02 UTC, Dr-Electron requested changes

2023-09-02 23:23 UTC, Dr-Electron approved these changes

2023-09-02 23:24 UTC, merged