Alias outputs doc
iotaledger/iota-wiki pull request #1153
Opened 2023-09-04 10:22 UTC by anistark

# Description of change

Added alias create, destroy docs.

## Links to any relevant issues

fixes issue #1111 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Documentation Enhancement

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [x] I have performed a self-review of my own changes
- [x] I have made sure that added/changed links still work

2023-09-04 20:31 UTC, Dr-Electron requested changes
Two broken links

2023-09-04 20:31 UTC, Dr-Electron commented on docs/build/iota-sdk/1.0.0/docs/how-tos/alias/create.mdx
> +3. Retry transaction until included [`Transaction`](../../references/nodejs/classes/Account/#retrytransactionuntilincluded) that was sent.
```suggestion
3. Retry transaction until included [`Transaction`](../../references/nodejs/classes/Account.md#retrytransactionuntilincluded) that was sent.
```

2023-09-04 20:31 UTC, Dr-Electron commented on docs/build/iota-sdk/1.0.0/docs/how-tos/alias/destroy.mdx
> +3. Retry transaction until included [`Transaction`](../../references/nodejs/classes/Account/#retrytransactionuntilincluded) that was sent.
```suggestion
3. Retry transaction until included [`Transaction`](../../references/nodejs/classes/Account.md#retrytransactionuntilincluded) that was sent.
```

2023-09-04 20:48 UTC, Dr-Electron commented
/create-preview

2023-09-04 20:57 UTC, Dr-Electron commented
Btw those examples are not aligned and don't create the same output. You should make sure the same useful output is created in the example. You can compare for example how we did it in the native token examples

2023-09-04 21:42 UTC, Dr-Electron commented
Also you don't import the correct lines of code 😅

2023-09-05 11:52 UTC, lucas-tortora requested changes

2023-09-05 11:52 UTC, lucas-tortora commented on docs/build/iota-sdk/1.0.0/docs/how-tos/alias/create.mdx
> +The Alias Output is a specific implementation of a UTXO state machine. Alias ID, the unique identifier of an instance of the deployed state machine, is generated deterministically by the protocol and
```suggestion
An [Alias Output](https://wiki.iota.org/tips/tips/TIP-0018/#alias-output) is a specific implementation of a UTXO state machine. The Alias ID, the unique identifier of an instance of the deployed state machine, is generated deterministically by the protocol and is not allowed to change in future state transitions.
```

2023-09-05 11:52 UTC, lucas-tortora commented on docs/build/iota-sdk/1.0.0/docs/how-tos/alias/create.mdx
> +Alias Output represents an alias account in the ledger with two control levels and a permanentAlias Address. The account owns other outputs that are locked under Alias Address. The account keeps trac
```suggestion
An Alias Output represents an alias account in the ledger with two control levels and a permanent Alias Address. The account owns other outputs that are locked under the Alias Address. The account keeps track of state transitions (`State Index` counter) and controlled foundries (`Foundry Counter`) and anchors the layer 2 state as metadata into the UTXO ledger.
```

2023-09-05 11:52 UTC, lucas-tortora commented on docs/build/iota-sdk/1.0.0/docs/how-tos/alias/create.mdx
> +2. Create an alias output transaction by calling the [`Account.create_alias_output()`](https://docs.rs/iota-sdk/latest/iota_sdk/wallet/account/struct.CreateAliasParams.html) function.
```suggestion
2. Create an Alias Output transaction by calling the [`Account.create_alias_output()`](https://docs.rs/iota-sdk/latest/iota_sdk/wallet/account/struct.CreateAliasParams.html) function.
```

2023-09-05 11:52 UTC, lucas-tortora commented on docs/build/iota-sdk/1.0.0/docs/how-tos/alias/create.mdx
> +3. Retry transaction until included [`Transaction`](https://docs.rs/iota-sdk/latest/iota_sdk/wallet/account/struct.Account.html#method.retry_transaction_until_included) that was sent.
```suggestion
3. Retry the [`Transaction`](https://docs.rs/iota-sdk/latest/iota_sdk/wallet/account/struct.Account.html#method.retry_transaction_until_included) until included.
```

2023-09-05 11:52 UTC, lucas-tortora commented on docs/build/iota-sdk/1.0.0/docs/how-tos/alias/create.mdx
> +https://github.com/iotaledger/iota-sdk/blob/develop/sdk/examples/how_tos/alias/create.rs#L43
```suggestion
https://github.com/iotaledger/iota-sdk/blob/develop/sdk/examples/how_tos/alias/create.rs#L43-L45
```

2023-09-05 11:52 UTC, lucas-tortora commented on docs/build/iota-sdk/1.0.0/docs/how-tos/alias/create.mdx
> +2. Create an alias output transaction by calling the [`Account.prepareCreateAliasOutput()`](../../references/nodejs/classes/Account.md#preparecreatealiasoutput) function.
```suggestion
2. Create an Alias Output transaction by calling the [`Account.prepareCreateAliasOutput()`](../../references/nodejs/classes/Account.md#preparecreatealiasoutput) function, and then [send](../../references/nodejs/classes/Account.md#send) it.
```

2023-09-05 11:52 UTC, lucas-tortora commented on docs/build/iota-sdk/1.0.0/docs/how-tos/alias/create.mdx
> +    https://github.com/iotaledger/iota-sdk/blob/develop/bindings/nodejs/examples/how_tos/alias/create.ts#L53
```suggestion
https://github.com/iotaledger/iota-sdk/blob/develop/bindings/nodejs/examples/how_tos/alias/create.ts#L53-L55
```

2023-09-05 11:52 UTC, lucas-tortora commented on docs/build/iota-sdk/1.0.0/docs/how-tos/alias/create.mdx
> +3. Retry transaction until included [`Transaction`](../../references/nodejs/classes/Account.md#retrytransactionuntilincluded) that was sent.
```suggestion
3. Retry  the [`Transaction`](../../references/nodejs/classes/Account.md#retrytransactionuntilincluded) until included.
```

2023-09-05 11:52 UTC, lucas-tortora commented on docs/build/iota-sdk/1.0.0/docs/how-tos/alias/create.mdx
> +https://github.com/iotaledger/iota-sdk/blob/develop/bindings/nodejs/examples/how_tos/alias/create.ts#L60
```suggestion
https://github.com/iotaledger/iota-sdk/blob/develop/bindings/nodejs/examples/how_tos/alias/create.ts#L60-L62
```

2023-09-05 11:52 UTC, lucas-tortora commented on docs/build/iota-sdk/1.0.0/docs/how-tos/alias/create.mdx
> +2. Create an alias output transaction by calling the [`Account.prepareCreateAliasOutput()`](../../references/python/iota_sdk/wallet/account.md#prepare_create_alias_output) function.
```suggestion
2. Prepare an Alias Output transaction by calling the [`Account.prepare_create_alias_output()`](../../references/python/iota_sdk/wallet/account.md#prepare_create_alias_output) function, and then [send](../../references/python/iota_sdk/wallet/account.md#send) it.
```

2023-09-05 11:52 UTC, lucas-tortora commented on docs/build/iota-sdk/1.0.0/docs/how-tos/alias/destroy.mdx
> +You can destroy an alias output by ID. If the alias still owns any outputs when you try to destroy it, you will get an error.
```suggestion
You can destroy an Alias Output using its ID. You will get an error if the alias still owns any outputs when you try to destroy it.
```

2023-09-05 11:52 UTC, lucas-tortora commented on docs/build/iota-sdk/1.0.0/docs/how-tos/alias/destroy.mdx
> +2. Destroy an alias output transaction by calling the [`Account.burn()`](https://docs.rs/iota-sdk/latest/iota_sdk/wallet/account/struct.Account.html#method.burn) function.
```suggestion
2. Destroy an Alias Output transaction by calling the [`Account.burn()`](https://docs.rs/iota-sdk/latest/iota_sdk/wallet/account/struct.Account.html#method.burn) function.
```

2023-09-05 11:52 UTC, lucas-tortora commented on docs/build/iota-sdk/1.0.0/docs/how-tos/alias/destroy.mdx
> +3. Retry transaction until included [`Transaction`](https://docs.rs/iota-sdk/latest/iota_sdk/wallet/account/struct.Account.html#method.retry_transaction_until_included) that was sent.
```suggestion
3. Retry the [`Transaction`](https://docs.rs/iota-sdk/latest/iota_sdk/wallet/account/struct.Account.html#method.retry_transaction_until_included) until included.
```

2023-09-05 11:52 UTC, lucas-tortora commented on docs/build/iota-sdk/1.0.0/docs/how-tos/alias/destroy.mdx
> +https://github.com/iotaledger/iota-sdk/blob/develop/sdk/examples/how_tos/alias/destroy.rs#L47
```suggestion
https://github.com/iotaledger/iota-sdk/blob/develop/sdk/examples/how_tos/alias/destroy.rs#L47-L49
```

2023-09-05 11:52 UTC, lucas-tortora commented on docs/build/iota-sdk/1.0.0/docs/how-tos/alias/destroy.mdx
> +    https://github.com/iotaledger/iota-sdk/blob/develop/bindings/nodejs/examples/how_tos/alias/destroy.ts#L56
```suggestion
https://github.com/iotaledger/iota-sdk/blob/develop/bindings/nodejs/examples/how_tos/alias/destroy.ts#L56-L58
```

2023-09-05 11:52 UTC, lucas-tortora commented on docs/build/iota-sdk/1.0.0/docs/how-tos/alias/destroy.mdx
> +2. Destroy an alias output transaction by calling the [`Account.preparedestroyalias()`](../../references/nodejs/classes/Account.md#preparedestroyalias) function.
```suggestion
2. Prepare the transaction to destroy an Alias Output by calling the [`Account.preparedestroyalias()`](../../references/nodejs/classes/Account.md#preparedestroyalias) function, and then [send](../../references/nodejs/classes/Account.md#send) it.
```

2023-09-05 11:52 UTC, lucas-tortora commented on docs/build/iota-sdk/1.0.0/docs/how-tos/alias/destroy.mdx
> +2. Destroy an alias output transaction by calling the [`Account.prepare_destroy_alias()`](../../references/python/iota_sdk/wallet/account.md#prepare_destroy_alias) function.
```suggestion
2. Destroy the transaction that will destroy the alias output by calling the [`Account.prepare_destroy_alias()`](../../references/python/iota_sdk/wallet/account.md#prepare_destroy_alias) function, and then [send](../../references/python/iota_sdk/wallet/account.md#send) it.
```

2023-09-07 07:44 UTC, Dr-Electron commented
> Btw those examples are not aligned and don't create the same output. You should make sure the same useful output is created in the example. You can compare for example how we did it in the native token examples

Are you going to work on it, or do you want to create another PR afterwards?

2023-09-11 21:48 UTC, anistark commented
> > Btw those examples are not aligned and don't create the same output. You should make sure the same useful output is created in the example. You can compare for example how we did it in the native token examples
> 
> Are you going to work on it, or do you want to create another PR afterwards?

Python output is left to match. Will open a PR to sdk and then come back to this. Let it stay open till then?

2023-09-12 11:57 UTC, anistark commented
The examples don't run on my system as usual. So, not able to test it out. nodejs and rust outputs are same now.
Here's my [PR](https://github.com/iotaledger/iota-sdk/pull/1212)

2023-09-18 10:53 UTC, luca-moser requested changes

2023-09-18 10:53 UTC, luca-moser commented on docs/build/iota-sdk/1.0.0/docs/how-tos/alias/destroy.mdx
> +You can destroy an alias output by ID. If the alias still owns any outputs when you try to destroy it, you will get an error.
This is not correct, whether an alias output owns other outputs or not does matter when you are destroying one. There is nothing in place from a protocol level that would prevent you from burning/deleting an alias output of which its address are still present in other addresses. Likewise, you could also theoretically create outputs which are owned by an Alias address which does not even exist.

Can you maybe point out how you came to this conclusion?

2023-09-25 07:49 UTC, Dr-Electron commented
> The examples don't run on my system as usual. So, not able to test it out. nodejs and rust outputs are same now.
> Here's my [PR](https://github.com/iotaledger/iota-sdk/pull/1212). If you're free, please check out python code.

Unrelated question, but:
Did you create an issue to track this btw? I forgot if you did 😅

2023-09-25 07:50 UTC, Dr-Electron commented
Can you please resolve the conflict. Let's get this merged 🦾

2023-09-25 09:19 UTC, luca-moser approved these changes

2023-09-26 07:56 UTC, luca-moser approved these changes

2023-09-26 08:41 UTC, merged