Refactor preparation of workflows
iotaledger/iota-wiki pull request #1189
Opened 2023-09-26 07:37 UTC by jlvandenhout

# Description of change

- Refactored the `prepare` action to only set up Yarn and create the dependency and build caches.
- Removed the `yarn prepare` call from the `prepare` action, to explicitly call it only in actions that require it.
- Added the `prepare` action to the `consistency` job, to speed it up.
- Changed the build caching to always restore and added a `clear` workflow that we can manually trigger through a dispatch or by commenting `/clear-build` on a PR, to renew Docusaurus build caches when needed.

## Links to any relevant issues

#1122

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [x] I have performed a self-review of my own changes
- [x] I have commented my code, particularly in hard-to-understand areas

2023-09-28 07:11 UTC, Dr-Electron approved these changes
LGTM

2023-09-28 07:44 UTC, Dr-Electron requested changes

2023-09-28 07:44 UTC, Dr-Electron commented on .github/workflows/clear.yml
There is no clear command in this action

2023-09-28 07:46 UTC, jlvandenhout commented on .github/workflows/clear.yml
> +        shell: bash
```suggestion
      - name: Prepare Yarn
        uses: ./.github/actions/prepare/
      - name: Clear Docusaurus build cache
        run: yarn clear
      - name: Prepare build
        run: yarn prepare
        shell: bash
```

2023-09-29 18:47 UTC, Dr-Electron approved these changes

2023-09-29 18:47 UTC, merged