Update Identity 1.0-rc JS API docs
iotaledger/iota-wiki pull request #1224
Opened 2023-10-06 14:43 UTC by eike-hass

# Description of change

Update Identity 1.0-rc JS API docs

## Type of change
- Documentation Fix

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [X] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [X] I have performed a self-review of my own changes
- [X] I have made sure that added/changed links still work
- [X] I have commented my code, particularly in hard-to-understand areas

2023-10-06 15:06 UTC, eike-hass commented
```
Exhaustive list of all broken links found:
Node version: v16.20.2

- On source page path = /identity.rs/libraries/wasm/api_reference/:
   -> linking to IJwsVerifier/ (resolved as: /identity.rs/libraries/wasm/api_reference/IJwsVerifier/)
```
@abdulmth do remember what the problem with the links was?

2023-10-07 21:40 UTC, Dr-Electron requested changes

2023-10-07 21:40 UTC, Dr-Electron commented on docs/build/identity.rs/1.0-rc.1/docs/libraries/wasm/api_reference.mdx
> +      An implementor of <a href='IJwsVerifier'>IJwsVerifier</a> that can handle
This link doesn't exist. Related to your above comment 🤔

2023-10-08 18:38 UTC, abdulmth commented
I think the issue is that `IJwsVerifier` exists in `identity_wasm_d.ts` but not in `identity_wasm.js` and it was referenced in `identity_wasm.js` (through the bindings) with `@link`. I would say just remove the `@link`  and use backticks instead.

2023-10-09 10:47 UTC, abdulmth approved these changes

2023-10-09 21:08 UTC, Dr-Electron approved these changes

2023-10-09 21:08 UTC, merged