Update shimmer-firefly-governance-guide.md
iotaledger/iota-wiki pull request #1261
Opened 2023-10-19 23:52 UTC by Phyloiota

Grammar, spelling and Make the guide generic for IOTA and Shimmer

# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

Be sure to reference any related issues by adding `fixes #issue_number`.

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Documentation Fix
- Documentation Enhancement

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [ ] I have performed a self-review of my own changes
- [ ] I have made sure that added/changed links still work
- [ ] I have commented my code, particularly in hard-to-understand areas

2023-10-20 00:03 UTC, Dr-Electron requested changes

2023-10-20 00:03 UTC, Dr-Electron commented on docs/learn/governance/shimmer-firefly-governance-guide.md
You forgot to rename this file

2023-10-20 14:47 UTC, Phyloiota commented on docs/learn/governance/shimmer-firefly-governance-guide.md
updated, thanks

2023-10-22 21:49 UTC, Dr-Electron approved these changes

2023-10-22 21:59 UTC, Dr-Electron approved these changes
I fixed some broken links and now it looks good to me.
Keep in mind that now some links on the wiki will be changed with all those changes.

Also you might want to change the image (shimmer-gov.png)

2023-10-22 22:46 UTC, Phyloiota commented
updated the images as suggested

2023-10-22 23:44 UTC, Dr-Electron approved these changes

2023-10-22 23:44 UTC, merged