Add scripts for preview and building subsections of the wiki
iotaledger/iota-wiki pull request #1292
Opened 2023-10-26 17:00 UTC by VmMad

# Description of change

Handle selection of sections of the wiki by splitting the config and selecting it with an environment variable.
Add scripts to start a subsection of the wiki directly: `yarn start:section:{section}`
Only show the selected section in the navbar

## Links to any relevant issues

Fixes #1254 

## Type of change

- Enhancement

## Change checklist

- [x] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [x] I have performed a self-review of my own changes
- [ ] I have made sure that added/changed links still work
- [ ] I have commented my code, particularly in hard-to-understand areas

2023-10-27 07:31 UTC, jlvandenhout requested changes

2023-10-27 07:31 UTC, jlvandenhout commented on package.json
> +    "start:section:maintain": "NODE_OPTIONS='--max-old-space-size=4096' SELECTED_SECTION='maintain' docusaurus start",
```suggestion
    "start:section:build": "SELECTED_SECTION='build' yarn start",
    "start:section:get-started": "SELECTED_SECTION='get-started' yarn start",
    "start:section:learn": "SELECTED_SECTION='learn' yarn start",
    "start:section:maintain": "SELECTED_SECTION='maintain' yarn start",
```

2023-10-27 09:59 UTC, VmMad commented
Comment for the reviewers:
I added the build scripts to this PR too, but they won't work unless the build configuration is updated. I didn't want to mess with your plugin configuration so if you want me to check this let me know

2023-10-27 14:52 UTC, jlvandenhout commented
I guess it's the redirect plugin that is complaining? So we'd need to do something similar to what you did in `contentPlugins.js`, but then in `articleRedirects.js` and the list of redirects in the `@docusaurus/plugin-client-redirects` plugin config I guess? I think it's fine to do that in this PR too 👍

2023-10-27 19:18 UTC, Dr-Electron commented
> I guess it's the redirect plugin that is complaining? So we'd need to do something similar to what you did in `contentPlugins.js`, but then in `articleRedirects.js` and the list of redirects in the `@docusaurus/plugin-client-redirects` plugin config I guess? I think it's fine to do that in this PR too 👍

I guess we could simplify that by not allowing builds to be split and in start we don't care about redirects? 🤔 
Do we need to build a single section? Wdyt @jlvandenhout

2023-10-29 07:56 UTC, jlvandenhout commented
@Dr-Electron That's true, so let's remove the build scripts.

2023-10-29 07:58 UTC, jlvandenhout requested changes

2023-10-29 07:58 UTC, jlvandenhout commented on package.json
> +    "build:section:maintain": "SELECTED_SECTION='maintain' yarn build",
We can remove these, because we will not use them for now anyways.

```suggestion
```

2023-10-29 08:00 UTC, jlvandenhout submitted a review, later dismissed

2023-10-30 21:04 UTC, Dr-Electron approved these changes

2023-11-01 09:16 UTC, jlvandenhout approved these changes

2023-11-01 09:21 UTC, merged