feat: UI polish
iotaledger/iota-wiki pull request #1321
Opened 2023-11-06 16:44 UTC by marc2332

Closes https://github.com/iotaledger/iota-wiki/issues/1277

2023-11-07 16:00 UTC, Dr-Electron requested changes
Only one small suggestion.


Also something else unrelated to this PR: There is still a "bug" I created. PF and FC float can not be directly entered. At least on my system.

2023-11-07 16:00 UTC, Dr-Electron commented on src/components/ManaCalculator/components/AdvancedSettingsValidator.tsx
> +          <div className='col col--2 horizontal-spaced text--center'>FC</div>
Let's get rid of all my past mistakes with this PR 😆 

```suggestion
          <div className='col col--2 horizontal-spaced text--center'>Performance factor</div>
          <div className='col col--2 horizontal-spaced text--center'>Fixed costs</div>
```

2023-11-07 16:35 UTC, begonaalvarezd commented on src/components/HomeLayout/styles.css
> +}
same here, couldnt we move these to the mana calculator folder?

2023-11-07 16:35 UTC, begonaalvarezd commented on src/components/HomeLayout/styles.css
> +}
im not a big fan of these atomic classes here, they are merely used in the mana calculator too so i think we could move them there

2023-11-07 16:35 UTC, begonaalvarezd commented on src/css/custom.css
> +.mana_calculator__compact {
we should try to avoid mana calculator specific code in this file too i think

2023-11-07 18:55 UTC, Dr-Electron commented on src/components/ManaCalculator/components/OutputForm.tsx
> +  });
Wondering what the decimals should be.
As the minimum amount of mana is micromana, 6 places after the decimals could theoretically make sense?
TPS is fine.
For the time I just picked 3 basically randomly which gives us a micro seconds resolution

2023-11-08 07:38 UTC, marc2332 commented on src/components/HomeLayout/styles.css
> +.mana_calculator__card {
Yes, that's a great idea, I don't know I put those in there :thinking:

2023-11-08 10:38 UTC, begonaalvarezd approved these changes

2023-11-08 13:22 UTC, Dr-Electron commented on src/components/ManaCalculator/components/OutputForm.tsx
> +  });
Any opinions on that? @begonaalvarezd @marc2332 ?

2023-11-08 15:32 UTC, Dr-Electron commented on src/components/ManaCalculator/components/OutputForm.tsx
> +  });
Solved in https://github.com/iotaledger/iota-wiki/pull/1324

2023-11-08 15:32 UTC, Dr-Electron approved these changes

2023-11-08 15:32 UTC, merged