Add Hornet Node Requirements
iotaledger/iota-wiki pull request #1525
Opened 2024-03-25 20:27 UTC by lucas-tortora

# Description of change

Added recommended harware reqs to run a hornet Node

## Links to any relevant issues

fixes https://github.com/iotaledger/devx/issues/347

## Type of change

- Documentation Enhancement

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [x] I have performed a self-review of my own changes
- [x] I have made sure that added/changed links still work
- [x] I have commented my code, particularly in hard-to-understand areas

2024-03-25 20:39 UTC, trungtt198x approved these changes

2024-03-26 10:31 UTC, Dr-Electron requested changes

2024-03-26 10:31 UTC, Dr-Electron commented on docs/maintain/hornet/2.0/docs/how_tos/using_docker.md
> +*
These are not Hornet requirements. Hornet requirements are mentioned [here](https://wiki.iota.org/hornet/getting_started/#recommended-requirements)

These are Wasp requirements and I would add them [here](https://wiki.iota.org/wasp/how-tos/running-a-node/)

Also the disk space should not just be a number. We should mention that it depends on your pruning config

2024-03-26 14:13 UTC, Dr-Electron approved these changes

2024-03-26 14:59 UTC, merged