Update deploy a smart contract page
iotaledger/iota-wiki pull request #1580
Opened 2024-05-28 14:57 UTC by Ginowine

# Description of change

This PR made some update to this [page on the wiki](https://wiki.iota.org/isc/how-tos/deploy-a-smart-contract/). The PR modifies the deploy.js script, and also added how to get your private key.

## Links to any relevant issues

fixes #1575  

## Type of change

- Documentation Enhancement

## Change checklist

- [x] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [x] I have performed a self-review of my own changes
- [x] I have made sure that added/changed links still work

2024-05-29 12:19 UTC, lucas-tortora requested changes
Just some small comments about style. Btw, you can create branches directly in this repo, no need for forks :)

2024-05-29 12:19 UTC, lucas-tortora commented on docs/build/isc/v1.0.0-rc.6/docs/how-tos/deploy-a-smart-contract.mdx
> +Follow [this article](https://helpwithpenny.com/export-and-import-metamask-private-key/) for further detail.
```suggestion
You can find more information in the [official Metamask Documentation](https://support.metamask.io/managing-my-wallet/secret-recovery-phrase-and-private-keys/how-to-export-an-accounts-private-key/).
```

2024-05-29 12:19 UTC, lucas-tortora commented on docs/build/isc/v1.0.0-rc.6/docs/how-tos/deploy-a-smart-contract.mdx
> +Follow [this article](https://helpwithpenny.com/export-and-import-metamask-private-key/) for further detail.
Please use official docs only for external references.

2024-05-29 12:19 UTC, lucas-tortora commented on docs/build/isc/v1.0.0-rc.6/docs/how-tos/deploy-a-smart-contract.mdx
> +:::info Private Key
```suggestion
:::info Export the Metamask Private Key
```

2024-05-29 12:19 UTC, lucas-tortora commented on docs/build/isc/v1.0.0-rc.6/docs/how-tos/deploy-a-smart-contract.mdx
> +
```suggestion
```

2024-05-29 12:19 UTC, lucas-tortora commented on docs/build/isc/v1.0.0-rc.6/docs/how-tos/deploy-a-smart-contract.mdx
> +- Click on the logo in the upper right corner
```suggestion
1. Click on the Metamask logo in the upper right corner.
```

2024-05-29 12:19 UTC, lucas-tortora commented on docs/build/isc/v1.0.0-rc.6/docs/how-tos/deploy-a-smart-contract.mdx
> +- Select the account you want to export
```suggestion
2. Select the account you want to export.
```

2024-05-29 12:19 UTC, lucas-tortora commented on docs/build/isc/v1.0.0-rc.6/docs/how-tos/deploy-a-smart-contract.mdx
> +- On the account page, click the menu (three dots) in the upper right corner, then click the "Account Details" button:
```suggestion
3. On the account page, click the menu (three dots) in the upper right corner, then click the "Account Details" button.
```

2024-05-29 12:19 UTC, lucas-tortora commented on docs/build/isc/v1.0.0-rc.6/docs/how-tos/deploy-a-smart-contract.mdx
> +- Click "Export Private Key"
```suggestion
4. Click on "Export Private Key".
```

2024-05-29 12:19 UTC, lucas-tortora commented on docs/build/isc/v1.0.0-rc.6/docs/how-tos/deploy-a-smart-contract.mdx
> +- To access your private key, you will now need to enter your wallet password. When done, click Confirm to continue.
```suggestion
5. Enter your wallet password to access your private key and click `Confirm` to continue.
```

2024-05-29 12:19 UTC, lucas-tortora commented on docs/build/isc/v1.0.0-rc.6/docs/how-tos/deploy-a-smart-contract.mdx
> +- Your private key will now be displayed. Click to copy it and save it in a safe place. (Note: For obvious reasons, we didn't show it in the screenshots below - but yours will be there.)
```suggestion
6. Your private key will now be displayed. Click to copy it and save it in a safe place. 
```

2024-05-29 12:19 UTC, lucas-tortora commented on docs/build/isc/v1.0.0-rc.6/docs/how-tos/deploy-a-smart-contract.mdx
> +- Your private key will now be displayed. Click to copy it and save it in a safe place. (Note: For obvious reasons, we didn't show it in the screenshots below - but yours will be there.)
```suggestion
6. Your private key will now be displayed. Click to copy it and save it in a safe place. 
```

2024-05-29 12:19 UTC, lucas-tortora commented on docs/build/isc/v1.0.0-rc.6/docs/how-tos/deploy-a-smart-contract.mdx
> +- Click close icon on top to close the screen.
```suggestion
```
This seems unnecessary.

2024-05-30 10:56 UTC, Ginowine commented
Thanks, I'll stop using my forked repo. working on your suggestion now.

2024-05-30 16:33 UTC, lucas-tortora approved these changes

2024-05-31 22:48 UTC, Dr-Electron commented on docs/build/isc/v1.0.0-rc.6/docs/how-tos/deploy-a-smart-contract.mdx
> +   Select "Create a JavaScript project" when prompted and answer the setup questions (you can just press enter to
```suggestion
   Select `Create a JavaScript project` (or whatever applies to your project) when prompted and answer the setup questions (you can press enter to
```

2024-05-31 23:07 UTC, Dr-Electron approved these changes

2024-05-31 23:08 UTC, merged