Update iota-token article
iotaledger/iota-wiki pull request #1599
Opened 2024-06-06 14:18 UTC by vivekjain23

Updating exchanges listing IOTA in the wiki and fixing the [issue](https://github.com/iotaledger/iota-wiki/issues/1582)

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [X] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [X] I have performed a self-review of my own changes
- [X] I have made sure that added/changed links still work
- [X] I have commented my code, particularly in hard-to-understand areas

2024-06-06 14:31 UTC, lucas-tortora requested changes

2024-06-06 14:31 UTC, lucas-tortora commented on docs/get-started/introduction/iota/iota-token.md
>  - [Bitvavo](https://bitvavo.com)
```suggestion
- [Binance](https://www.binance.com)
- [Binance.US](https://www.binance.us/en/home)
- [Bitfinex](https://www.bitfinex.com/)
- [Bitpanda](https://www.bitpanda.com)
- [Bitvavo](https://bitvavo.com)
- [Gate.io](https://www.gate.io/)
- [HTX](https://www.htx.com/)
- [OKX](https://www.okx.com/)
```

2024-06-06 14:31 UTC, lucas-tortora commented on docs/get-started/introduction/iota/iota-token.md
>  - [Bitvavo](https://bitvavo.com)
Let's alpha sort it :)

2024-06-07 08:47 UTC, vivekjain23 commented on docs/get-started/introduction/iota/iota-token.md
>  - [Bitvavo](https://bitvavo.com)
Sure, Lucas.

2024-06-07 10:52 UTC, lucas-tortora approved these changes

2024-06-12 15:13 UTC, lucas-tortora commented
@Ginowine and @salaheldinsoliman , could you please review this?

2024-06-12 15:38 UTC, salaheldinsoliman approved these changes
LGTM

2024-06-12 15:44 UTC, merged