Add IOTA SDK to Next
iotaledger/iota-wiki pull request #976
Opened 2023-06-08 15:06 UTC by lucas-tortora

# Description of change

* deleted iota.rs, iota.js and wallet.rs submodule entries
* added iota-sdk submodule
* added docs layout component to next section
* removed iota.rs, iota.js and wallet.rs from docs layout and added iota-sdk
* removed iota.rs, iota.js and wallet.rs from develop sidebar and added iota-sdk

## Links to any relevant issues

fixes https://github.com/iotaledger/iota-wiki/issues/957

## Type of change

- Documentation Enhancement

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [x] I have performed a self-review of my own changes
- [x] I have made sure that added/changed links still work
- [x] I have commented my code, particularly in hard-to-understand areas

2023-06-08 19:44 UTC, Dr-Electron requested changes

2023-06-08 19:44 UTC, Dr-Electron commented on src/next/components/DocsLayout/CoreLibrariesSection.tsx
> +            <Link to='/iota-sdk/simple_transaction/simple_transaction'>
```suggestion
            <Link to='/iota-sdk/how_tos/simple_transaction'>
```

2023-06-08 20:28 UTC, Dr-Electron reviewed
I guess you should update https://github.com/iotaledger/iota-wiki/blob/addSDKToNextSection/next/develop/explanations/what-is-shimmer/clients.md too? 
or do you want to do that in a separate PR?

2023-06-09 12:41 UTC, lucas-tortora commented
> I guess you should update https://github.com/iotaledger/iota-wiki/blob/addSDKToNextSection/next/develop/explanations/what-is-shimmer/clients.md too? or do you want to do that in a separate PR?

I think it'd be better once we merge the docs PRs in the SDK. So far, there aren't many links we can add, so we'll need to go back once we have everything

2023-06-12 11:54 UTC, Dr-Electron approved these changes
Ok, sounds good to me

2023-06-12 11:54 UTC, merged