Remove and replace iota-sdk in the-merge
iotaledger/iota-wiki pull request #982
Opened 2023-06-12 22:54 UTC by Dr-Electron

# Description of change

Removed and replaced the iota-sdk. Replaced the imports with [@saucelabs/docusaurus-theme-github-codeblock](https://github.com/saucelabs/docusaurus-theme-github-codeblock)

## Type of change

- Enhancement (a non-breaking change which adds functionality)
- Documentation Enhancement

## Change checklist

- [x] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [x] I have performed a self-review of my own changes
- [x] I have made sure that added/changed links still work
- [x] I have commented my code, particularly in hard-to-understand areas

2023-06-13 13:06 UTC, lucas-tortora requested changes
@Dr-Electron , is there a commit missing? You added the cli-wallet docs, but not the SDK, so we can't really test the `[@saucelabs/docusaurus-theme-github-codeblock](https://github.com/saucelabs/docusaurus-theme-github-codeblock)`

2023-06-13 13:38 UTC, lucas-tortora requested changes

2023-06-13 13:38 UTC, lucas-tortora commented on next/docusaurus.config.js
> +    path.resolve(__dirname, 'external/cli-wallet/static'),
```suggestion
  staticDirectories: [
    path.resolve(__dirname, 'external/*/static')
```

2023-06-13 15:26 UTC, Dr-Electron commented
> @Dr-Electron , is there a commit missing? You added the cli-wallet docs, but not the SDK, so we can't really test the `@saucelabs/docusaurus-theme-github-codeblock`

Wdym? Everything is there? Am I missing something?

2023-06-13 15:29 UTC, Dr-Electron commented
Hmmm. I see now. So the docs are there, but somehow not shown correctly? Will check later today...
But if you look at the changes, I can see the docs there... 🤔

2023-06-13 15:35 UTC, lucas-tortora commented
>  So the docs are there, but somehow not shown correctly? 

I think it was just a display bug or something, I can see them now  :)

2023-06-13 18:09 UTC, lucas-tortora commented on next/external/iota-sdk/docs/how_tos/accounts_and_addresses/list_accounts.mdx
> +https://github.com/iotaledger/iota-sdk/tree/develop/bindings/nodejs/examples/how_tos/accounts_and_addresses/list_accounts.ts
```suggestion
https://github.com/iotaledger/iota-sdk/tree/develop/bindings/nodejs/examples/how_tos/accounts_and_addresses/list-accounts.ts
```

2023-06-13 18:10 UTC, lucas-tortora commented on next/external/iota-sdk/docs/how_tos/accounts_and_addresses/list_addresses.mdx
> +https://github.com/iotaledger/iota-sdk/tree/develop/bindings/nodejs/examples/how_tos/accounts_and_addresses/list_addresses.ts
```suggestion
https://github.com/iotaledger/iota-sdk/tree/develop/bindings/nodejs/examples/how_tos/accounts_and_addresses/list-addresses.ts
```

2023-06-13 18:10 UTC, lucas-tortora commented on next/external/iota-sdk/docs/how_tos/accounts_and_addresses/list_outputs.mdx
> +https://github.com/iotaledger/iota-sdk/tree/develop/bindings/nodejs/examples/how_tos/accounts_and_addresses/list_outputs.ts
```suggestion
https://github.com/iotaledger/iota-sdk/tree/develop/bindings/nodejs/examples/how_tos/accounts_and_addresses/list-outputs.ts
```

2023-06-13 18:12 UTC, lucas-tortora commented on next/external/iota-sdk/docs/how_tos/accounts_and_addresses/create_address.mdx
> +https://github.com/iotaledger/iota-sdk/tree/develop/bindings/nodejs/examples/how_tos/accounts_and_addresses/create_address.ts
```suggestion
https://github.com/iotaledger/iota-sdk/tree/develop/bindings/nodejs/examples/how_tos/accounts_and_addresses/create-address.ts
```

2023-06-13 18:15 UTC, lucas-tortora commented on next/external/iota-sdk/docs/how_tos/accounts_and_addresses/check_balance.mdx
> +https://github.com/iotaledger/iota-sdk/tree/develop/bindings/nodejs/examples/how_tos/accounts_and_addresses/check_balance.ts
```suggestion
https://github.com/iotaledger/iota-sdk/tree/develop/bindings/nodejs/examples/how_tos/accounts_and_addresses/check-balance.ts
```

2023-06-13 18:17 UTC, lucas-tortora commented on next/external/iota-sdk/docs/how_tos/outputs/unlock_conditions.mdx
> +https://github.com/iotaledger/iota-sdk/tree/develop/bindings/nodejs/examples/how_tos/outputs/unlock_conditions.ts
```suggestion
https://github.com/iotaledger/iota-sdk/tree/develop/bindings/nodejs/examples/how_tos/outputs/unlock-conditions.ts
```

2023-06-13 18:18 UTC, lucas-tortora commented on next/external/iota-sdk/docs/how_tos/sign_and_verify_ed25519/sign_ed25519.mdx
> +https://github.com/iotaledger/iota-sdk/tree/develop/bindings/nodejs/examples/how_tos/sign_and_verify_ed25519/sign_ed25519.ts
```suggestion
https://github.com/iotaledger/iota-sdk/tree/develop/bindings/nodejs/examples/how_tos/sign_and_verify_ed25519/sign-ed25519.ts
```

2023-06-13 18:18 UTC, lucas-tortora commented on next/external/iota-sdk/docs/how_tos/sign_and_verify_ed25519/verify_ed25519_signature.mdx
> +https://github.com/iotaledger/iota-sdk/tree/develop/bindings/nodejs/examples/how_tos/sign_and_verify_ed25519/verify_ed25519_signature.ts
```suggestion
https://github.com/iotaledger/iota-sdk/tree/develop/bindings/nodejs/examples/how_tos/sign_and_verify_ed25519/verify-ed25519-signature.ts
```

2023-06-13 18:19 UTC, lucas-tortora commented on next/external/iota-sdk/docs/how_tos/simple_transaction/request_funds.mdx
> +https://github.com/iotaledger/iota-sdk/tree/develop/bindings/nodejs/examples/how_tos/simple_transaction/request_funds.ts
```suggestion
https://github.com/iotaledger/iota-sdk/tree/develop/bindings/nodejs/examples/how_tos/simple_transaction/request-funds.ts
```

2023-06-13 18:19 UTC, lucas-tortora commented on next/external/iota-sdk/docs/how_tos/simple_transaction/simple_transaction.mdx
> +https://github.com/iotaledger/iota-sdk/tree/develop/bindings/nodejs/examples/how_tos/simple_transaction/simple_transaction.ts
```suggestion
https://github.com/iotaledger/iota-sdk/tree/develop/bindings/nodejs/examples/how_tos/simple_transaction/simple-transaction.ts
```

2023-06-13 18:21 UTC, lucas-tortora commented on next/external/iota-sdk/static/img/iota_layers_overview.svg
didn't this get updated ?

2023-06-13 20:21 UTC, Dr-Electron commented on next/external/iota-sdk/static/img/iota_layers_overview.svg
I'm never sure about it 😆 But seems not. I also asked Thibault if we should update to the SDK layout in general

2023-06-13 23:01 UTC, jlvandenhout approved these changes
Other then the issues with the SDK content itself that we should probably fix upstream for now, like `/iota-sdk/how_tos/accounts_and_addresses/check_balance` crashing and some examples with a wrong URL, having the content in the Wiki repo and importing remote code seem to work quite well 👍

2023-06-14 14:03 UTC, lucas-tortora approved these changes
we should look into why how_tos/accounts_and_addresses/check_balance/ crashes due to CORS, but all in all, I think we can merge this into `the-merge` and sort it out in another PR, wdyt?

2023-06-14 14:38 UTC, jlvandenhout commented
> we should look into why how_tos/accounts_and_addresses/check_balance/ crashes due to CORS, but all in all, I think we can merge this into `the-merge` and sort it out in another PR, wdyt?

Not sure if those are related, though. I get CORS errors all over the place, and that's a server thing, not a client thing. `how_tos/accounts_and_addresses/check_balance` doesn't really crash for me. It just doesn't show any content.

But I agree that is unrelated to this PR, we can merge and then investigate separately.

2023-06-14 14:53 UTC, merged